services:
    app:
        build:
            context: .
            dockerfile: dockerfile
        volumes:
            - ./src:/src
            - ./http:/srv/http
        ports:
            - 8080:8080
            - 8081:8081
        tty: true
